---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql
  namespace: default
data:
  init.sql: |
    --
    -- Create application users.
    --
    CREATE USER myapp WITH PASSWORD 'devops123' SUPERUSER CREATEDB CREATEROLE LOGIN;

    --
    -- Clean up idle connections.
    --
    WITH inactive_connections AS (SELECT pid, usename FROM pg_stat_activity WHERE usename = 'myapp') SELECT pg_terminate_backend(pid) FROM inactive_connections;

    BEGIN;
    --
    -- Drop tables.
    --
    DROP TABLE IF EXISTS product;

    COMMIT;

    VACUUM full;

    -- Create Tables

    CREATE TABLE product (
      id SERIAL PRIMARY KEY,
      jdoc jsonb
    );

    CREATE INDEX product_inx ON product USING GIN (jdoc);
